# Generated by Django 5.0.7 on 2024-07-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='visits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
