# Generated by Django 5.0.7 on 2024-07-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_alter_urls_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
