# Generated by Django 5.0.7 on 2024-07-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_urls_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='unique_code',
        ),
    ]
