# Generated by Django 5.0.7 on 2024-07-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0004_remove_urls_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
