# Generated by Django 5.0.7 on 2024-07-12 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0005_alter_urls_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
