# Generated by Django 5.0.7 on 2024-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0006_urls_unique_code_alter_urls_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
